# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’
use_frameworks!

target 'Onyo' do

    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'Kingfisher', '~> 2.2'
    pod 'RealmSwift'
    pod 'SVProgressHUD'
    pod 'CHTCollectionViewWaterfallLayout', '0.9.2'

end

target 'OnyoTests' do

end

target 'OnyoUITests' do

end

