fastlane_version "1.39.0"
default_platform :ios

platform :ios do
  before_all do
    cocoapods
    increment_build_number
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "ios-challenge")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # sigh
    gym(scheme: "ios-challenge")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    # sigh
    gym(scheme: "ios-challenge")
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
